name: test_perftool.yml
on: [push]

jobs:
  test-perf-tool-arm:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Install perf
        run: sudo apt-get update && sudo apt-get install linux-tools-generic
      - name: Run perf list
        run: perf list
  test-perf-tool-x64:
    runs-on: ubuntu-latest
    steps:
      - name: Install perf
        run: sudo apt-get install linux-tools-generic
      - name: Run perf list
        run: perf list

