name: test_perftool.yml
on: [push]

jobs:
  test-perf-tool-arm:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Install perf
        run: sudo apt-get update && sudo apt-get install linux-tools-generic
      - name: Enable perf event paranoid flag
        run: sudo sysctl kernel.perf_event_paranoid=1
      - name: Run perf stat
        run: sudo perf stat -e cycles -a sleep 5

  test-perf-tool-x64:
    runs-on: ubuntu-latest
    steps:
      - name: Install perf
        run: sudo apt-get install linux-tools-generic
      - name: Enable perf event paranoid flag
        run: sudo sysctl kernel.perf_event_paranoid=1
      - name: Run perf stat
        run: sudo perf stat -e cycles -a sleep 5

